[package]
name = "sana"
version = "0.1.0"
edition = "2021"
authors = ["HenryCabarcas nerdtronikpay@gmail.com"]
readme = "./README.md"
license = "Mine"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yaml-rust = "0.4"